ios-defaults: &ios-defaults
  macos:
    xcode: "10.2.0"
  working_directory: ~/project
  environment:
    FL_OUTPUT_DIR: output
    FRONTEND_DIR: ~/project/karrot-frontend
    CORDOVA_DIR: ~/project/karrot-frontend/cordova
  shell: /bin/bash --login -eo pipefail

prepare-build-ios: &prepare-build-ios
  command: |
    cd ${CORDOVA_DIR}
    [ -x www ] && rm -f www
    ln -s dist-app-${CORDOVA_ENV} www
    cd ${CORDOVA_DIR}/config
    [ -x current ] rm -f current
    ln -s "${CORDOVA_ENV}" current
    cordova platform add ios

version: 2
jobs:
  install-dependencies:
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "karrot-frontend/package.json" }}
          - v1-dependencies-
      - run: yarn
      - save_cache:
          paths:
            - karrot-frontend/node_modules
          key: v1-dependencies-{{ checksum "karrot-frontend/package.json" }}

  install-fastlane-dependencies:
    <<: *ios-defaults
    steps:
      - checkout
      - restore_cache:
          key: 1-fastlane-{{ checksum "Gemfile.lock" }}
      - run:
          name: Install gems
          command: bundle check || bundle install --path vendor/cordova
      - save_cache:
          paths:
            - ~/vendor/cordova
          key: 1-fastlane-{{ checksum "Gemfile.lock" }}

  build-ios-dev:
    <<: *ios-defaults
    environment:
      FASTLANE_LANE: beta
    steps:
      - checkout
      - run:
          name: Install cordova
          command: yarn global add cordova@8.1.2
      - run:
          name: Build cordova app dev
          command: |
            cd ${CORDOVA_DIR}
            yarn build:cordova:dev
            mv dist dist-app-dev
      - run:
          <<: *prepare-build-ios
          name: Cordova platform add iOS dev
          environment:
            CORDOVA_ENV: dev
      - run:
          name: Fastlane
          command: bundle exec fastlane $FASTLANE_LANE

  deploy-ios-dev:
    <<: *ios-defaults
    steps:
      - checkout
      - run:
          name: Install cordova
          command: yarn global add cordova
      - run:
          <<: *prepare-build-ios
          name: Cordova platform add iOS prod
          environment:
            CORDOVA_ENV: prod
      - run:
          command: |
            cd ${CORDOVA_DIR}
            bundle install
            bundle exec fastlane beta

workflows:
  version: 2
  all-the-things:
    jobs:
      - install-dependencies
      - install-fastlane-dependencies
      - build-ios-dev:
          requires:
            - install-dependencies
            - install-fastlane-dependencies
