ios-defaults: &ios-defaults
  macos:
    xcode: "10.2.0"
  working_directory: /Users/distiller/project
  environment:
    FL_OUTPUT_DIR: output
    FRONTEND_DIR: /Users/distiller/project/karrot-frontend
    CORDOVA_DIR: /Users/distiller/project/karrot-frontend/cordova
  shell: /bin/bash --login -eo pipefail

prepare-build-ios: &prepare-build-ios
  command: |
    cd ${CORDOVA_DIR}
    rm -f www
    ln -s ../dist-app-${CORDOVA_ENV} www
    cd ${CORDOVA_DIR}/config
    rm -f current
    ln -s "${CORDOVA_ENV}" current
    cd ${CORDOVA_DIR}
    cordova platform add ios

version: 2
jobs:
  build-ios-dev:
    <<: *ios-defaults
    steps:
      - add_ssh_keys:
          fingerprints:
            - "83:43:65:26:c5:33:9c:7a:e8:13:a9:73:35:36:4f:35"
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run:
          name: Install packages for karrot-frontend
          command: |
            cd ${FRONTEND_DIR}
            yarn
      - run: yarn global add cordova@8.1.2
      - run:
          name: Build cordova app dev
          command: |
            cd ${FRONTEND_DIR}
            yarn build:cordova:dev
            mv dist dist-app-dev
      - run:
          <<: *prepare-build-ios
          name: Cordova platform add iOS dev
          environment:
            CORDOVA_ENV: dev
      - run: bundle install
      - run: bundle exec fastlane beta
      - store_artifacts:
          path: output

  deploy-ios-dev:
    <<: *ios-defaults
    steps:
      - checkout
      - run:
          name: Install cordova
          command: yarn global add cordova
      - run:
          <<: *prepare-build-ios
          name: Cordova platform add iOS prod
          environment:
            CORDOVA_ENV: prod
      - run:
          command: |
            cd ${CORDOVA_DIR}
            bundle install
            bundle exec fastlane beta

workflows:
  version: 2
  all-the-things:
    jobs:
      - build-ios-dev
